### ISSUE TITLE
Problem loggin in...

### ISSUE THREAD

**Issue by frolian** [kaysond/wow_ah#1]
Got this after running run_bot.php

[02-28-17 17:20:05] Login failed. Waiting 10 seconds and trying again.
Error constructing bot: Could not construct API. See API log. Could not log in.
HTTP GET request to world of warcraft login form did not successfully return bne
t login form. Redirected to https://eu.battle.net/login/en-us/?ref=https://eu.ba
ttle.net/oauth/authorize?response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%2
52Fworldofwarcraft.com%252Fauth%26scope%3Dname%26state%3Dr9O4su8B-18H2GiOtd5Wwzw
XeAKETSxc0Hqw%26client_id%3D5cn3p8ja2wm6d5vdhffccvkcp5k2mf8j&app=oauth.

What wrong did I do?

**Comment by kaysond** [comment]
What did you set $region and $lang to? By that url, it should be "eu" and "en-us", respectively. Its designed to work on all regions, but I only ever tested it on us. If that doesn't work, can you turn on API+HTTP logging and post that? (Make sure to delete your username/pw from the logs)

**Comment by kaysond** [comment]
Looks like the problem is that all eu regions and languages get sent to the eu.battle.net/en-us/ login regardless of the region and language. I don't have an eu account to test on, but I'll try to fix it...

**Comment by frolian** [comment]
Ok, thanks a lot.

**Comment by kaysond** [comment]
Can you do me a favor and tell me some urls? It'll help.
You'll have to log out first, then:
1) go to the wow website, record that url (should be like worldofwarcraft.com/es-es/)
2) mouse-over the login button, and record what url that goes to (like worldofwarcraft.com/es-es/login)
3) click the login button, then record the url of the login form (it does some redirects, I need the last one, probably like eu.battle.net/en-us/login)
4) log in, then record the url that you get to after login (back to worldofwarcraft.com/es-es)
5) go to the armory page for your character, and record that url (hopefully eu.battle.net/wow/es-es/charname/servername/simple)

**Comment by frolian** [comment]
1. go to the wow website, record that url
https://eu.battle.net/login/pl/

2. mouse-over the login button, and record what url that goes to
https://eu.battle.net/login/pl/?ref=http://eu.battle.net/pl/&app=com-root

3. click the login button, then record the url of the login form (it does some redirects, I need the last one)
https://eu.battle.net/login/en-us/?ref=https://eu.battle.net/oauth/authorize?response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fworldofwarcraft.com%252Fauth%26scope%3Dname%26state%3DTgLgVBnB-e7ra8-sTC6O6rrOszHPUYMxvPHI%26client_id%3D5cn3p8ja2wm6d5vdhffccvkcp5k2mf8j&app=oauth.

4. log in, then record the url that you get to after login
http://eu.battle.net/pl/

5. go to the armory page for your character, and record that url
http://eu.battle.net/wow/en/character/outland/Sajmons/

**Comment by kaysond** [comment]
I think that should be enough. Just in case, can you do these two as well:
Go to http://worldofwarcraft.com tell me where that redirects to

Then mouse over the login button on the top right of that page and record that.

Thanks!

**Comment by frolian** [comment]
1, https://worldofwarcraft.com/en-us/
2. https://worldofwarcraft.com/login

**Comment by kaysond** [comment]
Hopefully fixed! Let me know.

**Comment by frolian** [comment]
Fixed!

Got another problem but I think it's because of v8js crash or smth...

C:\php>php -f wow_ah_test.php
Session not restored. Please log in using login:<username>:<password>
login:mysecret@mailbox.com:mysecretp@ssword
Logging in...


#
# Fatal error in d:\chromium\v8\src\snapshot\natives-external.cc, line 122
# Check failed: holder_.
#

**Comment by kaysond** [comment]
yeah that looks like a v8js problem. if you're on windows, try using the php binaries I linked to in the readme
